import "oaidl.idl";
import "ocidl.idl";

[
	uuid( a2715f71-6d7c-4731-b251-7f4a4668c72b ),
	version( 1.0 )
]
library ClipboardToWord {

	importlib( "stdole2.tlb" );		

	interface IPlugin;

	[uuid( f31714c5-e3bf-42e7-ae74-e44c9796d735 ), dual, nonextensible, oleautomation]
	interface IApplication : IDispatch {
		
		[id( 0x10000010 ), propget]
		HRESULT Visible([out, retval] VARIANT_BOOL * pvis);
		[id( 0x10000010 ), propput]
		HRESULT Visible([in] VARIANT_BOOL vis);

		[id( 0x10000011 ), propget]
		HRESULT Monitor([out, retval] VARIANT_BOOL * pvis);
		[id( 0x10000011 ), propput]
		HRESULT Monitor([in] VARIANT_BOOL vis);

		[id( 0x10000020 )]
		HRESULT Quit(void);

		[id( 0x10000030 )]
		HRESULT LoadPlugin([in] BSTR path, [out, retval] IPlugin ** ppdispPlugin);

		[id( 0x10000035 )]
		HRESULT UnloadPlugin([in] BSTR path, [out, retval] VARIANT_BOOL * pres);
	};

	[uuid( ff80ab35-93ad-4441-a337-8cd2748ad522), dual, nonextensible, oleautomation]
	interface IPlugin : IDispatch {

		[id( 0x40000010)]
		HRESULT GetProperty([in] BSTR propertyname, [out, retval] BSTR * propertyvalue);
		[id( 0x40000015 )]
		HRESULT SetProperty([in] BSTR propertyname, [in] BSTR propertyvalue, [out, retval] VARIANT_BOOL * pres);

	};

	[uuid( a5ded517-3d32-41e8-b13a-f247209c4a9d ), dual, nonextensible, oleautomation]
	interface IClipboardEvents : IDispatch {
		
		[id( 0x20000010 )]
		HRESULT ClipboardUpdate(void);

		[id( 0x20000020 )]
		HRESULT NewBitmapOnClipboard(void);

		[id( 0x20000030 )]
		HRESULT BitmapSavedToTempFile([in] BSTR filepath);

		[id( 0x20000040 )]
		HRESULT Quit(void);
	};

	[uuid( 7f2a0ab1-33f0-4429-a996-b5578395defd ), dual, nonextensible, oleautomation]
	interface IApplicationEvents : IDispatch {

		[id( 0x30000010 )]
		HRESULT OnQuit(void);
	};

	[uuid( 2867c8f1-7a59-445c-b2d2-77ef58a3ac8d )]
	coclass Application {

		[default]			interface IApplication;
		[default, source]	interface IClipboardEvents;
		[source]			interface IApplicationEvents; 

	};

	[uuid( bb60afb3-15b7-4afd-9f8c-89d0ba7a6d88 )]
	coclass ClipboardEvents {
		[default] interface IClipboardEvents;
	};

	[uuid( 537c3d54-07b1-426d-8c65-ca2b054a41a7)]
	coclass ClipboardEventsPlugin {
		[default] interface IPlugin;
		interface IClipboardEvents;
	};

	[uuid( c4af1965-ba78-4bac-a5a0-69f8b5347d31 )]
	coclass ApplicationEvents {
		[default] interface IApplicationEvents;
	};


};